/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ClienteDAO;
import modelo.EntidadCliente;
import modelo.EntidadProducto;
import modelo.EntidadVendedor;
import modelo.ProductoDAO;
import modelo.VendedorDAO;

/**
 *
 * @author Rios
 */
public class IfrmMantenimiento extends javax.swing.JInternalFrame {
    ClienteDAO cliDao = new ClienteDAO();
    ProductoDAO proDao = new ProductoDAO();
    VendedorDAO venDao = new VendedorDAO();
    EntidadCliente cli = new EntidadCliente();
    EntidadProducto pro = new EntidadProducto();
    EntidadVendedor ven = new EntidadVendedor();
    
    DefaultTableModel modeloCliente = new DefaultTableModel();
    DefaultTableModel modeloProducto = new DefaultTableModel();
    DefaultTableModel modeloVendedor = new DefaultTableModel();
    
    int idCliente;
    int r;
    
    public IfrmMantenimiento() {
        initComponents();
        listarCliente();
        listarProducto();
        listarVendedor();
    }
    
    void listarCliente(){
        List<EntidadCliente> lista = cliDao.listar();
        modeloCliente=(DefaultTableModel)tablaCliente.getModel();
        Object[]ob=new Object[5];
        for(int i = 0; i <lista.size(); i++){
            ob[0]=lista.get(i).getId();
            ob[1]=lista.get(i).getDni();
            ob[2]=lista.get(i).getNom();
            ob[3]=lista.get(i).getDir();
            ob[4]=lista.get(i).getEstado();
            modeloCliente.addRow(ob);
        }
        tablaCliente.setModel(modeloCliente);
    }
    
    void listarProducto(){
        modeloProducto = (DefaultTableModel) tablaProducto.getModel();
        List<EntidadProducto> lista = proDao.listarProducto();
        Object[] object = new Object[5];
        for (int i = 0; i < lista.size(); i++) {
            object[0] = lista.get(i).getId();
            object[1] = lista.get(i).getNom();
            object[2] = lista.get(i).getPre();
            object[3] = lista.get(i).getStock();
            object[4] = lista.get(i).getEstado();
            modeloProducto.addRow(object);
        }
        tablaProducto.setModel(modeloProducto);
    }
    
    void listarVendedor(){
        modeloVendedor = (DefaultTableModel) tablaVendedor.getModel();
        List<EntidadVendedor> lista = venDao.listarVendedor();
        Object[] object = new Object[5];
        for (int i = 0; i < lista.size(); i++) {
            object[0] = lista.get(i).getId();
            object[1] = lista.get(i).getDni();
            object[2] = lista.get(i).getNom();
            object[3] = lista.get(i).getTel();
            object[4] = lista.get(i).getEstado();
            modeloVendedor.addRow(object);
        }
        tablaVendedor.setModel(modeloVendedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        cboEstadoCliente = new javax.swing.JComboBox<>();
        btnAgregarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        txtStockProducto = new javax.swing.JTextField();
        cboEstadoProducto = new javax.swing.JComboBox<>();
        btnAgregarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDniVendedor = new javax.swing.JTextField();
        txtNombreVendedor = new javax.swing.JTextField();
        txtCelularVendedor = new javax.swing.JTextField();
        cboEstadoVendedor = new javax.swing.JComboBox<>();
        btnAgregarVendedor = new javax.swing.JButton();
        btnEliminarVendedor = new javax.swing.JButton();
        btnModificarVendedor = new javax.swing.JButton();
        btnNuevoVendedor = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();
        btnCliente = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();

        setBackground(new java.awt.Color(241, 196, 15));
        setPreferredSize(new java.awt.Dimension(650, 490));

        jTabbedPane1.setBackground(new java.awt.Color(44, 62, 80));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(650, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DNI:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 13, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRES:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIRECCION:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 69, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ESTADO:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 103, -1, -1));

        txtDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniClienteKeyTyped(evt);
            }
        });
        jPanel4.add(txtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 13, 208, -1));

        txtNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreClienteKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 38, 208, -1));
        jPanel4.add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 67, 208, -1));

        cboEstadoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1", "0" }));
        jPanel4.add(cboEstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 98, 208, -1));

        btnAgregarCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/plus.png"))); // NOI18N
        btnAgregarCliente.setText("AGREGAR");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        btnActualizarCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rotate.png"))); // NOI18N
        btnActualizarCliente.setText("ACTUALIZAR");
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        btnEliminarCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel_1.png"))); // NOI18N
        btnEliminarCliente.setText("ELIMINAR");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        btnNuevoCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rec.png"))); // NOI18N
        btnNuevoCliente.setText("NUEVO");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "NOMBRES", "DIRECCION", "ESTADO"
            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 210));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CLIENTE", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRECIO:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 44, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STOCK:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 69, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ESTADO:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, -1, -1));

        txtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyTyped(evt);
            }
        });
        jPanel6.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 12, 230, -1));

        txtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoKeyTyped(evt);
            }
        });
        jPanel6.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 230, -1));

        txtStockProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockProductoKeyTyped(evt);
            }
        });
        jPanel6.add(txtStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 230, -1));

        cboEstadoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1", "0" }));
        jPanel6.add(cboEstadoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 94, 230, -1));

        btnAgregarProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/plus.png"))); // NOI18N
        btnAgregarProducto.setText("AGREGAR");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel6.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        btnEliminarProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel_1.png"))); // NOI18N
        btnEliminarProducto.setText("ELIMINAR");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel6.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        btnModificarProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnModificarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rotate.png"))); // NOI18N
        btnModificarProducto.setText("MODIFICAR");
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        btnNuevoProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rec.png"))); // NOI18N
        btnNuevoProducto.setText("NUEVO");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });
        jPanel6.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jPanel7.setBackground(new java.awt.Color(44, 62, 80));

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "STOCK", "ESTADO"
            }
        ));
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProducto);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("PRODUCTO", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(44, 62, 80));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NOMBRES:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CELULAR:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ESTADO:");

        txtDniVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniVendedorActionPerformed(evt);
            }
        });
        txtDniVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniVendedorKeyTyped(evt);
            }
        });

        txtNombreVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreVendedorKeyTyped(evt);
            }
        });

        txtCelularVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularVendedorKeyTyped(evt);
            }
        });

        cboEstadoVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "1", "0" }));

        btnAgregarVendedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAgregarVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/plus.png"))); // NOI18N
        btnAgregarVendedor.setText("AGREGAR");
        btnAgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVendedorActionPerformed(evt);
            }
        });

        btnEliminarVendedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEliminarVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel_1.png"))); // NOI18N
        btnEliminarVendedor.setText("ELIMINAR");
        btnEliminarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVendedorActionPerformed(evt);
            }
        });

        btnModificarVendedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnModificarVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rotate.png"))); // NOI18N
        btnModificarVendedor.setText("MODIFICAR");
        btnModificarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVendedorActionPerformed(evt);
            }
        });

        btnNuevoVendedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnNuevoVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rec.png"))); // NOI18N
        btnNuevoVendedor.setText("NUEVO");
        btnNuevoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(53, 53, 53)
                                    .addComponent(txtDniVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(25, 25, 25)
                                    .addComponent(cboEstadoVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarVendedor)
                            .addComponent(btnAgregarVendedor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevoVendedor)
                            .addComponent(btnModificarVendedor))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCelularVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDniVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cboEstadoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarVendedor)
                            .addComponent(btnModificarVendedor))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEliminarVendedor)
                                .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(btnNuevoVendedor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCelularVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(44, 62, 80));

        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DNI", "NOMBRES", "CELULAR", "ESTADO"
            }
        ));
        tablaVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVendedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaVendedor);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("VENDEDOR", jPanel3);

        btnCliente.setBackground(new java.awt.Color(44, 62, 80));
        btnCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/group.png"))); // NOI18N
        btnCliente.setText("CLIENTE");
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnProducto.setBackground(new java.awt.Color(44, 62, 80));
        btnProducto.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/package.png"))); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnVendedor.setBackground(new java.awt.Color(44, 62, 80));
        btnVendedor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnVendedor.setForeground(new java.awt.Color(255, 255, 255));
        btnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/businessman.png"))); // NOI18N
        btnVendedor.setText("VENDEDOR");
        btnVendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnProducto)
                    .addComponent(btnVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnVendedorActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        eliminarCliente();
        limpiarTablaCliente();
        listarCliente();
        nuevoCliente();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        agregarCliente();
        limpiarTablaCliente();
        listarCliente();
        nuevoCliente();
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        actualizarCliente();
        limpiarTablaCliente();
        listarCliente();
        nuevoCliente();
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        nuevoCliente();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        int fila = tablaCliente.getSelectedRow();
        if(fila==1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }else{
            idCliente = Integer.parseInt(tablaCliente.getValueAt(fila, 0).toString());
            String dni = tablaCliente.getValueAt(fila, 1).toString();
            String nom = tablaCliente.getValueAt(fila, 2).toString();
            String dir = tablaCliente.getValueAt(fila, 3).toString();
            String es = tablaCliente.getValueAt(fila, 4).toString();
            txtDniCliente.setText(dni);
            txtNombreCliente.setText(nom);
            txtDireccionCliente.setText(dir);
            cboEstadoCliente.setSelectedItem(es);
        }
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void txtDniVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniVendedorActionPerformed

    private void tablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseClicked
        int fila = tablaProducto.getSelectedRow();
        if (fila >= 0) {
            String nom = tablaProducto.getValueAt(fila, 1).toString();
            String precio = tablaProducto.getValueAt(fila, 2).toString();
            String stock = tablaProducto.getValueAt(fila, 3).toString();
            String estado = tablaProducto.getValueAt(fila, 4).toString();
            txtNombreProducto.setText(nom);
            txtPrecioProducto.setText(precio);
            txtStockProducto.setText(stock);
            cboEstadoProducto.setSelectedItem(estado);
        }
    }//GEN-LAST:event_tablaProductoMouseClicked

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        String nom = txtNombreProducto.getText();
        double pre = Double.parseDouble(txtPrecioProducto.getText());
        int stock = Integer.parseInt(txtStockProducto.getText());
        String estado = cboEstadoProducto.getSelectedItem().toString();
        pro.setNom(nom);
        pro.setPre(pre);
        pro.setStock(stock);
        pro.setEstado(estado);
        proDao.agregar(pro);
        LimpiarTablaProducto();
        listarProducto();
        nuevoProducto();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        int fila = tablaProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        } else {
            int id = Integer.parseInt(tablaProducto.getValueAt(fila, 0).toString());
            String nom = txtNombreProducto.getText();
            double pre = Double.parseDouble(txtPrecioProducto.getText());
            int stock = Integer.parseInt(txtStockProducto.getText());
            String estado = cboEstadoProducto.getSelectedItem().toString();
            pro.setNom(nom);
            pro.setPre(pre);
            pro.setStock(stock);
            pro.setEstado(estado);
            pro.setId(id);
            proDao.actualizar(pro);
            JOptionPane.showMessageDialog(this, "Producto Actualizado con Exito");
            LimpiarTablaProducto();
            listarProducto();
            nuevoProducto();
        }
    }//GEN-LAST:event_btnModificarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        int fila = tablaProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        } else {
            int id = Integer.parseInt(tablaProducto.getValueAt(fila, 0).toString());
            proDao.delete(id);
            JOptionPane.showMessageDialog(this, "Producto Eliminado");
        }
        LimpiarTablaProducto();
        listarProducto();
        nuevoProducto();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        nuevoProducto();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void tablaVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVendedorMouseClicked
        int fila = tablaVendedor.getSelectedRow();
        if (fila >= 0) {
            String id = tablaVendedor.getValueAt(fila, 0).toString();
            ven = venDao.listarVendedorId(id);
            String dni = tablaVendedor.getValueAt(fila,1).toString();
            String nom = tablaVendedor.getValueAt(fila, 2).toString();
            String cel = tablaVendedor.getValueAt(fila, 3).toString();
            String estado = tablaVendedor.getValueAt(fila, 4).toString();
            txtDniVendedor.setText(dni);
            txtNombreVendedor.setText(nom);
            txtCelularVendedor.setText(cel);
            cboEstadoVendedor.setSelectedItem(estado);
        }
    }//GEN-LAST:event_tablaVendedorMouseClicked

    private void btnAgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVendedorActionPerformed
        String nom = txtNombreVendedor.getText();
        String dni = txtDniVendedor.getText();
        String cel = txtCelularVendedor.getText();
        String estado = cboEstadoVendedor.getSelectedItem().toString();
        String user = nom.substring(0, 2).concat(dni.substring(0, 2));
        ven.setDni(dni);
        ven.setNom(nom);
        ven.setTel(cel);
        ven.setEstado(estado);
        ven.setUser(user);
        venDao.agregar(ven);
        LimpiarTablaVendedor();
        listarVendedor();
        nuevoVendedor();
    }//GEN-LAST:event_btnAgregarVendedorActionPerformed

    private void btnModificarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVendedorActionPerformed
        modificarVendedor();
    }//GEN-LAST:event_btnModificarVendedorActionPerformed

    private void btnEliminarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVendedorActionPerformed
        int fila = tablaVendedor.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        } else {
            int id = Integer.parseInt(tablaVendedor.getValueAt(fila, 0).toString());
            venDao.delete(id);
            JOptionPane.showMessageDialog(this, "Vendedor Eliminado");
        }
        LimpiarTablaVendedor();
        listarVendedor();
        nuevoVendedor();
    }//GEN-LAST:event_btnEliminarVendedorActionPerformed

    private void btnNuevoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVendedorActionPerformed
        nuevoVendedor();
    }//GEN-LAST:event_btnNuevoVendedorActionPerformed

    private void txtDniClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniClienteKeyTyped
        char car = evt.getKeyChar();
        if((car<'0'||car>'9'))
            evt.consume();
    }//GEN-LAST:event_txtDniClienteKeyTyped

    private void txtStockProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockProductoKeyTyped
      char car = evt.getKeyChar();
        if((car<'0'||car>'9'))
            evt.consume();
    }//GEN-LAST:event_txtStockProductoKeyTyped

    private void txtCelularVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularVendedorKeyTyped
        char car = evt.getKeyChar();
        if((car<'0'||car>'9'))
            evt.consume();
    }//GEN-LAST:event_txtCelularVendedorKeyTyped

    private void txtDniVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniVendedorKeyTyped
       char car = evt.getKeyChar();
        if((car<'0'||car>'9'))
            evt.consume();
    }//GEN-LAST:event_txtDniVendedorKeyTyped

    private void txtNombreVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreVendedorKeyTyped
        char car = evt.getKeyChar();
        if(Character.isDigit(car)){
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtNombreVendedorKeyTyped

    private void txtNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteKeyTyped
        char car = evt.getKeyChar();
        if(Character.isDigit(car)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreClienteKeyTyped

    private void txtNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isDigit(car)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreProductoKeyTyped

    private void txtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoKeyTyped
        char car = evt.getKeyChar();
        if(((car < '0')||(car > '9')) && (car != KeyEvent.VK_BACK_SPACE) && (car != '.')){
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioProductoKeyTyped
        
    void agregarCliente(){
        if(txtDniCliente.getText().equals("")&&txtNombreCliente.getText().equals("")&&txtDireccionCliente.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Casillas vacias, por favor rellene para poder continuar");
        }else{
        String dni = txtDniCliente.getText();
        String nom = txtNombreCliente.getText();
        String dir = txtDireccionCliente.getText();
        String es = cboEstadoCliente.getSelectedItem().toString();
        Object[] ob = new Object[4];
        ob[0]=dni;
        ob[1]=nom;
        ob[2]=dir;
        ob[3]=es;
        cliDao.add(ob);
        }
    }
    void actualizarCliente(){
        int fila=tablaCliente.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una fila");
        }else{
        String dni = txtDniCliente.getText();
        String nom = txtNombreCliente.getText();
        String dir = txtDireccionCliente.getText();
        String es = cboEstadoCliente.getSelectedItem().toString();
        Object[] obj = new Object[5];
        obj[0]=dni;
        obj[1]=nom;
        obj[2]=dir;
        obj[3]=es;
        obj[4]=idCliente;
        cliDao.actualizar(obj);
        }
    }
    void eliminarCliente(){
        int fila = tablaCliente.getSelectedRow();
        int ids = Integer.parseInt(tablaCliente.getValueAt(fila, 0).toString());
        if(fila==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila");
        }else{
          cliDao.eliminar(ids);
        }
    }
    void nuevoCliente(){
        txtNombreCliente.setText("");
        txtDniCliente.setText("");
        txtDireccionCliente.setText("");
        cboEstadoCliente.setSelectedItem(0);
        txtDniCliente.requestFocus();
    }
    void limpiarTablaCliente(){
        for (int i = 0; i < modeloCliente.getRowCount(); i++) {
            modeloCliente.removeRow(i);
            i=i-1;
        }
    }
    
    void nuevoProducto() {
        txtNombreProducto.setText("");
        txtPrecioProducto.setText("");
        txtStockProducto.setText("");
        cboEstadoProducto.setSelectedIndex(0);
        txtNombreProducto.requestFocus();
    }

    void LimpiarTablaProducto() {
        for (int i = 0; i < tablaProducto.getRowCount(); i++) {
            modeloProducto.removeRow(i);
            i = i - 1;
        }
    }
    
    void modificarVendedor() {
        int fila = tablaVendedor.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        } else {
            int id = Integer.parseInt(modeloVendedor.getValueAt(fila, 0).toString());
            String dni = txtDniVendedor.getText();
            String nom = txtNombreVendedor.getText();            
            String cel= txtCelularVendedor.getText();
            String estado = cboEstadoVendedor.getSelectedItem().toString();            
            ven.setDni(dni);
            ven.setNom(nom);
            ven.setTel(cel);
            ven.setEstado(estado);
            ven.setId(id);
            r=venDao.actualizar(ven);
            if(r==1){
                JOptionPane.showMessageDialog(this, "Vendedor Actualizado con Exito..!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error");
            }
            LimpiarTablaVendedor();
            listarVendedor();
            nuevoVendedor();
        }
    }

    void nuevoVendedor() {
        txtNombreVendedor.setText("");
        txtDniVendedor.setText("");
        txtCelularVendedor.setText("");
        cboEstadoVendedor.setSelectedIndex(0);
        txtDniVendedor.requestFocus();
    }

    void LimpiarTablaVendedor() {
        for (int i = 0; i < modeloVendedor.getRowCount(); i++) {
            modeloVendedor.removeRow(i);
            i = i - 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAgregarVendedor;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnEliminarVendedor;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnModificarVendedor;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoVendedor;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JComboBox<String> cboEstadoCliente;
    private javax.swing.JComboBox<String> cboEstadoProducto;
    private javax.swing.JComboBox<String> cboEstadoVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaVendedor;
    private javax.swing.JTextField txtCelularVendedor;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtDniVendedor;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreVendedor;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtStockProducto;
    // End of variables declaration//GEN-END:variables
}
